### ISSUE TITLE
Multiple edit windows open 

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#297] opened 2015-03-29 23:46 UTC
1.  Double click any node
2. double click same node again

it is possible to have the same edit window open multiple times.

**Comment by AaronBehunin** [comment] 2015-03-31 16:55
Here is a screenshot
![double](https://cloud.githubusercontent.com/assets/10467750/6924259/1224e224-d78c-11e4-9b7c-275274688c0f.png)

**Comment by cchriste** [comment] 2016-03-17 20:52
One might argue that this is by design, but I agree that it can be confusing. 
Assigning to @scrgiorgio for consideration.

**Comment by scrgiorgio** [comment] 2016-03-18 08:13
This issue was moved to sci-visus/nvisusio#481

**Closed by scrgiorgio** 2016-03-18 08:13 UTC
Labels: Bug
