### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by hoangthaiduong** [sci-visus/visus-issues#289] opened 2015-03-21 09:13 UTC
We should have a way to let the user do the following using the GUI (not XML file):

1) Enable/disable caching
2) Specify where to save the data
3) Specify a size limit of the cache directory (when the limit is reached, we delete, for example, the least recently used cache files)

Currently, we can do 1) and 2) only through an XML config file, which is inconvenient at best and frustrating at worst. In particular, I've been generating image sequences from a not-too-small dataset, and often have to leave the program running overnight to get all the images. More than once I returned to the computer in the morning only to find out the hard drive was full because of the cache. It would be nice to make the cache option more explicit and allow the user to have some direct control over it.

**Comment by scrgiorgio** [comment] 2015-07-09 16:13
1) and 2)  When you open a dataset a ModVisusAccess is created by default (for remote datasets). 'Enable caching" at run time would mean to remove the old access and create a new one... not simple :( Let me think a little more about it

3) mmmmmmm It's clear to me that you want something like "the cache must take less than Xgb" but I don't know how to do that. When you say "the least recently used cache files"... what is that for a file? I just open a file, read it and close it. Could be the "last modification time"? But in that case I would probably remove the coarse file/blocks (i.e. the first to be written). What could be a good policy for removal?

**Comment by cchriste** [comment] 2015-07-09 16:54
1) enable/disable is very tricky as Giorgio says. Maybe we can use a *uuid* for automatic caching so it doesn't interfere with explicitly specified caching (which is still going to be important to support, e.g., on-demand conversion).
2) Regarding where to save the data, we already have a global $(VisusCacheDirectory) accessible on all platforms. Any automatic caching scheme should utilize this, and it should be configurable in the visus.config.
3) This is a big one, and we need it for our on-demand conversion work as well. Like the first two, there exists a manual solution, _rm -r_, but it's not very satisfactory. Consider whether we want to control cache size on a per-dataset level or as a group, say, everything in $(VisusCacheDirectory).

**Comment by ptbremer** [comment] 2015-07-09 22:13
For the caching policy we probably would like something like the last recently accessed. So can we just set the modification time each time we access a file (say with uptime(char* filename, time)) ?

The use case is that we have many people accusing a growing number of files and as the cache grows some of these will not be used anymore and can be deleted.

**Comment by cchriste** [comment] 2015-07-09 22:17
3) last access time will probably work surprisingly well: the coarse data will be removed last since it is most often accessed when _any_ dataset is read. We can always start here and see how it goes, since it's easy to implement (I hope!).

**Comment by cchriste** [comment] 2016-03-17 20:49
For the cache issue that @ptbremer and I were discussing, this is related to the on-demand conversion system at LLNL and a script has been written to effect this policy. Called periodically with cron it takes care of the cache cleanup using the proposed LRU policy, but never deleting metadata (.idx files) and works as desired. There is potentially an issue of the script not getting called meanwhile the cache grows uncontrollably, but for the application at Livermore this is not really feasible since the disk I/O is so slow (20-40MB/s for their nfs mounted storage). 

However, aside from this aside, @hoangthaiduong's original issue is still valid. There is still no way to automate caching on the client side. The issue is complex since we sometimes want explicit caching and other times want implicit caching.

**Comment by scrgiorgio** [comment] 2016-03-18 08:14
This issue was moved to sci-visus/nvisusio#486

**Closed by scrgiorgio** 2016-03-18 08:14 UTC
Labels: Feature Request, Priority Normal, ViSUS
