### ISSUE TITLE
Isosurfaces become black when refined 

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#295] opened 2015-03-28 06:28 UTC
I am displaying an isosrface in the usual green color
when it refines to full resolution it turns black

**Comment by cchriste** [comment] 2016-03-17 23:36
I cannot reproduce this. Either it's been fixed or is a system-specific issue. 
Reassigning to @pascucci for clarification.

**Comment by scrgiorgio** [comment] 2016-03-18 08:14
This issue was moved to sci-visus/nvisusio#482

**Closed by scrgiorgio** 2016-03-18 08:14 UTC
Labels: Bug

**Comment by scrgiorgio** [comment] 2016-03-18 17:49
I think this has been resolved some months ago

2016-03-18 0:36 GMT+01:00 Cameron Christensen <notifications@github.com>:
