### ISSUE TITLE
xml save has several problems

### ISSUE THREAD

**Issue by pascucci** [sci-visus/visus-issues#293] opened 2015-03-28 05:55 UTC
The xml save has several problems that makes it impossible to save scenes for a demo.
Key points:
- order of the elements gets changed
- color of isosurfaces is cahnged (very had to take back since you have to edit each color)
- palette gets modified.
There may be other issues. 
This is making impossible to save scenes for demos (i wanted to make one on Tue...)

**Comment by scrgiorgio** [comment] 2015-05-12 16:15
https://github.com/sci-visus/nvisusio/commit/a9c760c29e2963eee0953065a2b8bdefe8416caf

1) fixed with this commit
2) already fixed in the past
3) Need more details. Cannot reproduce (i.e. saved and loaded back the scene and the palette looks the same)

**Comment by scrgiorgio** [comment] 2016-03-18 08:14
This issue was moved to sci-visus/nvisusio#484

**Closed by scrgiorgio** 2016-03-18 08:14 UTC
Labels: Bug, Priority High
