### ISSUE TITLE
rendering is slower than it should be

### ISSUE THREAD

**Issue by cchriste** [sci-visus/visus-issues#346] opened 2015-09-15 20:03 UTC
Now it appears that every mouse wheel update is passed to the app, resulting in a very unpleasant experience while zooming, especially when getting closer to objects.

Zoom once relied on a timer associated with the scroll wheel input in order to behave properly. This appears to have been removed.

Assigning to Duong since he was the last to work on the camera, but it may well be something for Giorgio.

**Comment by cchriste** [comment] 2015-09-16 21:33
I'm making this more general because I have been trying to create a movie to show how interactive our system is, and I simply cannot succeed. It is too sluggish. 

I'm reassigning to Giorgio but anyone is welcome to look into this. 

Though there is a fps configuration in VisusViewer, it does not appear to have any effect on performance.

**Comment by scrgiorgio** [comment] 2015-09-17 06:41
I remember duong working on the camera code lately. 
So I'm reassigning. Duong do you have some hours to spend on it?
(honestly for me it's not clear where to start) 
Otherwise reassign to me.

**Comment by anikethvenkat** [comment] 2015-09-17 12:23
Hi,

I don’t think its a camera problem… I did some elementary profiling and found the following:

- Time between the mouse event and frame start varies between 100-500ms. Why? OpenGL thread is waiting for the MessageManager to be unlocked.
Is there a way we can optimize this (one zoom event triggers multiple zoom steps (zoom animation) perhaps, so that we won’t wait for the lock at every step)?

frame 128 start 1442489550139ms
frame took 2ms
swap buffers took 3ms
frame 129 start 1442489550145ms
frame took 3ms
swap buffers took 4ms
on mouse wheel triggered repaint at 
zoom start 1442489550152ms
zoom took 1ms and triggered repaint
main message unlocked at 140ms
frame 132 start 1442489550293ms
frame took 1ms
swap buffers took 2ms
frame 133 start 1442489550296ms
frame took 2ms
swap buffers took 4ms
on mouse wheel triggered repaint at 
zoom start 1442489550303ms
zoom took 1ms and triggered repaint
main message unlocked at 151ms
frame 136 start 1442489550454ms
frame took 1ms
swap buffers took 1ms
on mouse wheel triggered repaint at 
zoom start 1442489550457ms
zoom took 1ms and triggered repaint
main message unlocked at 99ms
frame 139 start 1442489550556ms
frame took 1ms
swap buffers took 1ms

- Swap buffers takes unusually long time sometimes! Why? Bug in swap buffer implementation? We are NOT sleeping in sleepIfRenderingTooFast.
What is this in juice_OpenGL_osx.h
“        #if VISUS_OPTION_JUCE
        setSwapInterval(0); //this can cause poor performace? seems I don't have any alternative...
        #endif "

frame 143 start 1442489550572ms
frame took 0ms
swap buffers took 111ms
on mouse wheel triggered repaint at 
zoom start 1442489550683ms
zoom took 2ms and triggered repaint
frame 146 start 1442489550685ms
frame took 1ms
swap buffers took 147ms
on mouse wheel triggered repaint at 
zoom start 1442489550833ms
zoom took 2ms and triggered repaint
frame 149 start 1442489550835ms
frame took 2ms
swap buffers took 146ms
frame 150 start 1442489550984ms
frame took 1ms
swap buffers took 466ms
on mouse wheel triggered repaint at 
zoom start 1442489551723ms
zoom took 1ms and triggered repaint
frame 153 start 1442489551756ms
frame took 1ms
swap buffers took 0ms

zoom start 1442491051301ms
zoom took 1ms and triggered repaint
main message unlocked at 535ms
frame 189 start 1442491051837ms

Thanks,
Aniketh

**Comment by scrgiorgio** [comment] 2015-09-17 16:56
can you try now? I upgraded JUCE and removed the setSwapInterval

**Comment by anikethvenkat** [comment] 2015-09-17 17:30
Same result…

swap buffers took 193ms
swap buffers took 127ms
swap buffers took 1ms
11:28:46.8438 INFO RENDERARRAY.249 dtype(float32) dimension(128 128 63) dims(128 128 63) transfered on GPU in msec(19)
swap buffers took 4ms
swap buffers took 1ms
swap buffers took 1ms
swap buffers took 313ms

**Comment by scrgiorgio** [comment] 2015-09-18 05:52
I tried to track down where the problem is.
Quoting Cameron: "behavior changed between jun29 (working well) and jul1 (not good)".

I did:

git log --after="2015-06-29 00:00" --before="2015-07-01 23:59" > possible.txt

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/2bec2e0da72540b993b5365c758f2303caac1025
Merge: d91000c 7d9cc0d
Author: scrgiorgio <scrgiorgio@gmail.com>
Date:   Wed Jul 1 19:58:08 2015 +0200
    Merge pull request #369 from cchriste/develop
    fix ondemand for linux and windows builds (forking external process d…

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/7d9cc0d52379de799d7ea3a7bf4b8ac8f21f307b
Author: Cameron Christensen <cam@sci.utah.edu>
Date:   Wed Jul 1 10:42:43 2015 -0600
    fix ondemand for linux and windows builds (forking external process disabled on windows)

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/d91000c3067084a35685944f9d64dd0517d3edfe
Merge: e005eba ba932a5
Author: scrgiorgio <scrgiorgio@gmail.com>
Date:   Wed Jul 1 17:56:35 2015 +0200
    Merge pull request #368 from sci-visus/tutorial
    fixes and examples from tutorial (most notably: resolves sci-visus/visus-issues#318)

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/e005eba9f44a04833472c3e57794f141175f7c11
Merge: e3c2479 ef0a1e1
Author: scrgiorgio <scrgiorgio@gmail.com>
Date:   Mon Jun 29 22:30:50 2015 +0200
    Merge pull request #352 from sci-visus/amy_current_new_develop
    Amy current new develop

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/ef0a1e1ef8c1698ef93b9db85d6714d371b58b7b
Author: Amy Gooch <amy.a.gooch@gmail.com>
Date:   Mon Jun 29 11:17:30 2015 -0500
    Try to fix spacing to conform to develop

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/40f1cbd464ed5581f830f87c14975e4d5ecc5866
Author: Amy Gooch <amy.a.gooch@gmail.com>
Date:   Mon Jun 29 11:09:08 2015 -0500
    Fixing indenting and removing old code that was moved into experimental

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/3b8c65c12b25c8f2bb4c98e458f158743369dd54
Author: Amy Gooch <amy.a.gooch@gmail.com>
Date:   Mon Jun 29 09:54:39 2015 -0500
    Fixed Time slider length to be 100% of window: https://github.com/sci-visus/visus-issues/issues/310

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/6e7f8776331b419877f2c7a5151aca96e6d885e4
Author: Amy Gooch <amy.a.gooch@gmail.com>
Date:   Mon Jun 29 09:42:18 2015 -0500
    remove DS_store from tracking

[CANNOT BE THE PROBLEM]
https://github.com/sci-visus/nvisusio/commit/344e5286595d231ed8abcbc69de2bef268fb1cb3
Author: Amy Gooch <amy.a.gooch@gmail.com>
Date:   Mon Jun 29 09:39:50 2015 -0500
    added two missing icons to file; updated stats view to be the correct class

[MAYBE?]
https://github.com/sci-visus/nvisusio/commit/6f80070b32390340ed789897b703ed6d726e61d0
Merge: ebcbc50 e3c2479
Author: Amy Gooch <amy.a.gooch@gmail.com>
Date:   Mon Jun 29 08:40:37 2015 -0500
    Merge branch 'develop' of https://github.com/sci-visus/nvisusio into amy_current_new_develop
    Conflicts:
    	visuscpp/appkit/nodes/visus_timenode.cpp
    	visuscpp/appkit/nodes/visus_timenode.h
    	visuscpp/gui/visus_gui_resources.cpp
    	visuscpp/gui/visus_gui_resources.generated.cpp


Unless I'm missing something the only problem I can see is the raycast.
Cameron, the slowness shows up using both the raycaster and the old shader?).
Cameron (or maybe anikethvenkat?) can you do a little more debugging?

**Comment by cchriste** [comment] 2015-09-18 07:00
Giorgio, will you please check the conversation on slack? I already figured
this out. Sorry I didn't also send a message to you about it.

Cameron

**Comment by scrgiorgio** [comment] 2015-09-18 07:04
np

2015-09-18 9:00 GMT+02:00 Cameron Christensen <notifications@github.com>:

**Comment by cchriste** [comment] 2015-09-18 23:36
After updating the system to use fast draft-quality rendering, we are again in a very usable state. I'm changing the name of this bug to reflect our concern with rendering in general, and assigning it to Aniketh who will continue profiling as we discussed earlier.

**Comment by scrgiorgio** [comment] 2016-03-18 08:10
This issue was moved to sci-visus/nvisusio#461

**Closed by scrgiorgio** 2016-03-18 08:10 UTC
Labels: Bug, microscopy, Priority High
