### ISSUE TITLE
Windows x64 Visus Startup error  /  Missing *.lock

### ISSUE THREAD

**Issue by AaronBehunin** [sci-visus/visus-issues#202] opened 2015-01-12 17:48 UTC
when you double click "runvisus-win"  returns "Missing  *.lock file"
![error1](https://cloud.githubusercontent.com/assets/10467750/5707758/95e75e60-9a48-11e4-87bc-57350962a1e7.png)

**Comment by AaronBehunin** [comment] 2015-01-15 18:40
Here is a video of the process:

**Comment by scrgiorgio** [comment] 2015-01-21 10:23
if you don't give more details, I don't know where to start.
is it a problem of RM *.lock inside the bat file? 
are you using the latest version? 
if visus is crashing what is the call stack? etc etc.
Please don't add issues without adding a lot of details.

**Comment by AaronBehunin** [comment] 2015-01-21 18:18
I am using the latest Windows x64 directx build.  After downloading and extracting i double click run-Visus.bat.    Program fails to start and gives error shown on screenshot

**Comment by scrgiorgio** [comment] 2015-02-12 14:43
Cameron, the 'latest' build means really latest or it's an old binary (==is buildbot generating packages?)

For Aaron: try to see if just a problem of a flag about 'ignore if file does not exist'.
Under linux is 'rm -f'... in windows?

**Comment by scrgiorgio** [comment] 2015-02-17 07:21
No comments?

**Comment by cchriste** [comment] 2016-03-17 19:42
Closing this bug since there is no way to reproduce and @AaronBehunin is no longer here.

**Closed by cchriste** 2016-03-17 19:42 UTC
